# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package + Docker image

on:
  push:
    branches: ["master"]
  release:
    types: [created]

jobs:
  build-test-and-push-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Compute JAR version
      id: ver
      run: |
          PATCH=$((GITHUB_RUN_NUMBER - 1))
          VERSION="1.0.${PATCH}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Computed JAR version: $VERSION"

    - name: Update pom.xml version
      run: |
          mvn -B versions:set \
            -DnewVersion=${{ steps.ver.outputs.version }} \
            -DgenerateBackupPoms=false    

    - name: run test + build
      run: mvn -B clean verify --file pom.xml

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

      
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
           ${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:${{ steps.ver.outputs.version }}
           ${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:latest

    - name: Deploy (pull+run) + Check output
      run: |
       IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:${{ steps.ver.outputs.version }}
       docker pull $IMAGE
       OUTPUT=$(docker run --rm $IMAGE)
       echo "$OUTPUT"

 
